### ISSUE TITLE
English name for de_at is misleading

### ISSUE THREAD

**Issue by crazysmc** [bezzdev/search_crafting#4]
The English translation for de_at would be Austrian German or a dialect of German with a made-up spelling (it's not translated like we actually write in Austria at all, more of a joke feature) but it has nothing to do with Pennsylvania Dutch and is not related to the USA at all.

https://github.com/bezzdev/search_crafting/blob/12351f3702a751518f0f7c1531a440dc49723314/src/js/languages.js#L19C70-L19C88

**Comment by bezzdev** [comment]
Thanks for pointing this out.
The anglicized versions of these language names were auto-generated so are very prone to errors.

I will amend this and push an update soon.

**Comment by bezzdev** [comment]
Fixed and live.
